import ant from 'ant-design-vue/es/locale/en_US'
import youibot from 'youibot-plus/lib/locale/lang/en'

export default {
  ...ant,
  ...youibot,
  schedule: {
    executePrompt: 'Are you sure you want to perform a task now?',
    statusConfirm: { '0': 'Are you sure you want to disable the task?', '1': 'Are you sure you want to enable the task?' },
    suspend: 'Suspend',
    normal: 'Normal',
    ban: 'Prohibit',
    allow: 'Allow',
    givePerform: 'Waiver of execution',
    once: 'Execute once',
    immediateExecution: 'Execute immediately',
    cronExecutesExpressions: 'Cron execution expression',
    isConcurrently: 'Allow concurrent',
    planningStrategy: 'Planning strategy',
    callsTarget: 'Call target',
    taskStatus: 'Task status',
    nextExecutionTime: 'Next execution time',
    executeExpression: 'Execute expression',
    callingTargetString: 'Call target string',
    taskGroup: 'Task grouping',
    taskName: 'Task name',
    taskNumber: 'Task number',
    serial: 'Serial number'
  },
  dictManage: {
    status: { '0': 'normal', '1': 'Deactivate' },
    N: 'No',
    Y: 'Yes',
    dictionaryKeysValue: 'Dictionary key value',
    warning: 'For unified specifications, please be sure to use lowercase letters and underscores to define page acquisition, such as:',
    builtIn: 'Built in system',
    dictionaryType: 'Dictionary type',
    dictionaryName: 'Dictionary name',
    dictionaryKeys: 'Dictionary primary key',
    serial: 'Serial number'
  },
  systemTool: {
    parameter: {
      primarykey: 'Parameter primary key',
      parameterName: 'Parameter name',
      parametersKeyName: 'Parameter key name',
      parametersKeyValue: 'Parameter key value',
      builtIn: 'Built in system',
      note: 'remarks',
      warning: 'Unified specification: please be sure to use capital letters and underline definitions Page acquisition, such as:',
      Y: 'yes',
      N: 'no'
    }
  },
  operatManual: {
    tabItems: { first: 'AGV problem', second: 'System operation problems', version: 'TMS-v4. 0.0. pdf' }
  },
  errorDict: {
    errorInfo: 'Abnormal information',
    errorCode: 'Exception code'
  },
  version: {
    versionName: 'System version',
    updateDate: 'Update date',
    systemName: 'System name',
    changeLog: 'Update content',
    upLoad: 'Upload',
    uploadNewVersion: 'Upload new version',
    downCurrentVersion: 'Download current version'
  },
  operateLog: {
    operateLog: 'Operation log',
    unnormal: 'Abnormal',
    normal: 'Normal',
    other: 'Other',
    pc: 'PC end',
    mobile: 'Mobile terminal',
    delete: 'Delete',
    operateDetail: 'Detailed',
    operate: 'Operation',
    responseTime: 'Response time',
    operateTime: 'Operation time',
    operateStatus: 'Operation status',
    operateAddress: 'Place of operation',
    hostIp: 'Host',
    companyName: 'Corporate name',
    operateMemeber: 'Operator',
    operateType: 'Operation type',
    sysModule: 'System module'
  },
  loginLog: {
    loginLog: 'Login log',
    operate: 'Operation',
    loginTime: 'Login time',
    operateInfo: 'Operation information',
    operateSystem: 'Operating system',
    browser: 'Browser',
    ownedCompany: 'Affiliated company',
    loginLocation: 'Login location',
    loginStatus: 'Login status',
    institutionalEnquiry: 'Please select superior organization',
    loginName: 'Logon name',
    loginAddress: 'Login address',
    serialNumber: 'Serial number'
  },
  systemParams: {
    PleaseEnterCurrentNumber: 'Please enter the current number of times',
    pleaseEnterSystemName: 'Please enter the system name',
    curTime: 'Current times',
    curName: 'Current name',
    pda: 'PDA end',
    pc: 'PC end',
    revise: 'Modify',
    tips: 'Warm tip: if you need to modify the brand label on the login page, please upload the picture according to the size',
    loginErrorTimes: 'System login error number setting',
    name: 'System name',
    loginLogo: 'Login page logo'
  },
  station: {
    stationDesc: 'Job description',
    stationType: 'Job classification',
    stationName: 'Post name',
    stationCode: 'Post code'
  },
  mechanism: {
    orderNum: 'Sort',
    deptName: 'Organization name',
    parentName: 'Superior organization'
  },
  userManage: {
    role: 'Role',
    phone: 'Phone number',
    email: 'E-mail address',
    job: 'Post',
    mechanism: 'Affiliated institution',
    name: 'User name',
    account: 'User name'
  },
  roleManage: {
    menuRights: 'Menu permissions',
    dataRights: 'Data authority',
    roleName: 'Role name'
  },
  menuManage: {
    icon: 'Icon',
    visible: 'Menu status',
    path: 'Address',
    orderNum: 'Sort',
    btn: 'Button',
    menu: 'Menu',
    menuType: 'Menu type',
    menuName: 'Menu name',
    parentName: 'Superior menu',
    component: 'Component name',
    url: 'Menu address',
    main: 'Home directory',
    name: 'Menu name'
  },
  menu: {
    monitor: {
      config: 'Business monitoring',
      statisticalKanban: 'Statistical Kanban',
      task: 'Task monitoring',
      taskHistory: 'Task history query',
      taskRealTime: 'Task real-time monitoring',
      AGVOperate: 'AGV operation monitoring',
      AGVTask: 'AGV task monitoring',
      WMS: 'WMS monitoring',
      expection: 'Abnormal monitoring',
      interface: 'Interface monitoring'
    },
    task: {
      manage: 'task management',
      taskList: 'Task list',
      taskApart: 'Task Disassembly',
      defineTemplate: 'Define template',
      manualOrder: 'Manual order',
      processArrange: 'Process arrangement'
    },
    business: {
      config: 'Business configuration',
      factory: 'Plant Hierarchy ',
      deviceParams: 'Equipment parameters',
      deviceAccount: 'Equipment account',
      IOTParams: 'IOT parameters',
      AgvConfig: 'AGV configuration',
      storageParams: 'Storage parameters',
      vehicleInfo: 'Vehicle information',
      materialInfo: 'Material information',
      elementGroup: 'Element grouping',
      pointPriority: 'Point priority'
    },
    system: {
      setting: 'System settings',
      tool: 'System tools',
      menu: 'Menu management',
      parameter: 'Parameter management',
      dict: 'Dictionary management',
      schedule: 'Scheduled task',
      monitor: 'System monitoring',
      logLogin: 'Login log',
      logOperate: 'Operation log',
      version: 'System version',
      exceptionDict: 'Exception dictionary',
      operatManual: 'Operation manual',
      config: 'system configuration',
      systemParams: 'system parameter',
      mechanism: 'Institutional level',
      station: 'Post allocation',
      role: 'Role configuration',
      user: 'user management ',
      main: 'home directory'
    }
  },
  Login: {
    confirmPassword: 'Confirm password',
    newPassword: 'New password',
    oldPassword: 'Old password',
    forgetPsw: 'Forget password',
    loginAuto: 'Next automatic login',
    loginErr: 'Incorrect user name or password, login failed!',
    noPassword: 'Please input a password',
    noUserName: 'Enter one user name',
    password: 'Password',
    userName: 'User name',
    login: 'Sign in',
    tip: 'Log in to your account'
  },
  message: {
    passwordNotSame: 'The two passwords are different',
    passwordErr: 'The password must consist of 8 to 30 letters and numbers',
    selectPlaceholderErr: 'The selection cannot be empty',
    placeholderErr: 'Content cannot be empty',
    nameErr: 'Name cannot be empty',
    ipFormatErr: 'IP input error',
    emailFormatErr: 'Incorrect email input',
    phoneFormatErr: 'Wrong telephone input',
    codeFormatErr: 'Numbers can only be letters or numbers or a combination of both',
    delete: 'Delete',
    stop: 'Deactivate',
    normal: 'Normal',
    submit: 'Submit',
    cancel: 'Cancel',
    ok: 'Confirm',
    Tips: 'Tips',
    delTips: 'Are you sure to delete this data?',
    placeholder: 'Please enter'
  },
  system: {
    fileTypeErr: 'The file format is incorrect',
    operationSuccess: 'Operation successful',
    all: 'Whole',
    hint: 'Tips',
    remark: 'Remarks',
    saveSuccess: 'Saved successfully',
    no: 'No',
    yes: 'Yes',
    createTime: 'Creation time',
    status: 'State',
    fail: 'Fail',
    success: 'Success',
    options: 'Operation',
    hide: 'Hide',
    show: 'Display',
    add: 'Newly added',
    del: 'Delete',
    edit: 'Edit',
    import: 'Import',
    export: 'Export',
    clear: 'Empty',
    search: 'Search',
    loginOut: 'Log out',
    changePsw: 'Change Password'
  }
}
